### ISSUE TITLE
user instructions

### ISSUE THREAD

**Issue by A80SafeSkies** [ethayer/user-lock-manager#12]
Self-admitted box of rocks needs a walk-through how to use this. I find no user manual of sorts or tutorial video beyond that to install. How to I assign code and schedule when active? Help?

**Comment by ethayer** [comment]
Please ask this question on the community forum here, as this does not pertain to a code issue.
http://community.smartthings.com/t/lock-code-manager/12280

**Comment by ethayer** [comment]
Closing as this is not a fixable code issue.

**Comment by A80SafeSkies** [comment]
You are the developer. Cannot you help me in leaning how to use it? The
support team at Smartthings could not even figure it out with what I gave
them. I cannot tell which version I have or anything. Downloaded okay, just
seems incomplete.

**Comment by ethayer** [comment]
I would likely be the one to answer your questions in the community forum.  This is just not the place for these kinds of questions.

I am only 1 person.  The community forum hosts many more people who could answer this question.  I don't have time to do it right now since I am currently with my newborn, but there may be someone with a little extra time on the community forum who would like to help a lot sooner than I could.

**Comment by A80SafeSkies** [comment]
Okay, it's out there. Not trying to disturb or be a dick. I purchased the
ST Hub under the impression that their software did this. $100 later, they
cannot help me. Hub works, your add-on obviously did something because I
inadvertently deleted a code (???) which was a default from Schlage. Now
I'm afraid to mess with it. I simply need to know how to navigate it the
way you laid it out. Maybe it can't do what I need....which means the ST
was a waste.

Congrats on the newborn. Everyone says, but true. Best damn thing in your
life, bar none. My only son, raised myself, is 23 and at his first
post-college job in TX. I'm presently in GA. I hurt sometimes missing him
so badly. Best times of my otherwise very full life. Take every advantage
to enjoy and love them up!

Mike
Wish me luck in this mess. Making me anxious
