### ISSUE TITLE
How exactly do I use this?

### ISSUE THREAD

**Issue by golharam** [ethayer/user-lock-manager#15]
There are two groovy files.  Which one do a add and how do I access it from my iPhone?  It didn't appear as a SmartApp even after publishing

**Comment by Sirchuk** [comment]
One is a custom device type so it won't show as a smart app. You would need
to add the device type (I suggest zwave lock #2 or something else to
differentiate it from the other) to the lock within the web IDE under the
locks properties.

The other is a smart app which should show up under your apps.

**Comment by apenny13** [comment]
Hi - 

How do you add the device type?  I have a smartthings hub but do I need to add this as a new device? If so, how do I switch it?  I am also wondering what additional funcationality it has. 

Thanks for any help you can provide.

**Comment by ethayer** [comment]
Refer to the community page for these types of questions.

https://community.smartthings.com/t/lock-code-manager/

Specifically, your question is answered in this post:
https://community.smartthings.com/t/lock-code-manager/12280/280

**Comment by apenny13** [comment]
Awesome, it worked perfectly.  Love the software. 
Mary

**Comment by curfew3749** [comment]
Could anyone comment on the keypad settings.  I cant find any documentation.  I see that I can set routines for things like arm/away routine, disarm routine, arm/stay routine, etc.  I don't see what triggered each of those items.  Any explanation would be appreciated.  It would be awesome if I could trigger a routing that arms SHM if the lock is locked, and trigger another routine that disarms SHM if the lock is unlocked.
