### ISSUE TITLE
Usage count not incrementing and SMS notifications not sending

### ISSUE THREAD

**Issue by PatAllee** [ethayer/user-lock-manager#16]
Greetings - likely "user error" as I am extremely "novice". Everything appears to be functioning as expected however the usage count is not incremeting for any Users (I created 3 for testing) nor am I receiving texts to phone on events such as "on entry", etc. Lock is a Kwikset SmartCode 914 (so far loving the potential of your app by the way - it's exactly want I needed).

**Comment by PatAllee** [comment]
I may have solved the issue. I installed a range extender today and app is now generating usage counts and texts on events. Prior to the extender, the program would allow creation of new codes, lock/unlock, etc. only - no usage counts nor SMS to mobile. Will continue to test over next several days.

**Comment by ethayer** [comment]
Oh, interesting.  Seems like the app would send the program codes over and over until one finally stuck, but the lock only tries to tell the hub of an action only once.  If the packet is lost, then the event is lost and not reported.

Good info to know.
