### ISSUE TITLE
zwave-lock.groovy 

### ISSUE THREAD

**Issue by golharam** [ethayer/user-lock-manager#18]
When pasting this groovy file to make an app, I get the error:

No signature of method: script14397485816001646905943.metadata() is applicable for argument types: (script14397485816001646905943$_run_closure1) values: [script14397485816001646905943$_run_closure1@63283bd1] Possible solutions: getMetadata(), getState(), setState(java.lang.Object), metaClass(groovy.lang.Closure)

**Comment by ethayer** [comment]
This file is for the device type driver.  Paste this code into the DeviceType section of the IDE rather than a new app.

https://community.smartthings.com/t/lock-code-manager/12280/280
