### ISSUE TITLE
Would it be possible for you to setup an ST IDE Integration

### ISSUE THREAD

**Issue by tonesto7** [ethayer/user-lock-manager#20]
It would be great to add your repo to SmartThings IDE and just pull in your code updates from there without having to copy and paste

**Comment by caseybristow** [comment]
I second this!

**Comment by richardpowellus** [comment]
:+1:

**Comment by ethayer** [comment]
Done, I think. Use this repo: 
https://github.com/ethayer/SmartThingsPublic

**Comment by ethayer** [comment]
I'm going to be still making changes and tracking issues on this repo, however.

**Comment by claytonjn** [comment]
You shouldn't have to make a whole new repo, if you don't want to manage two code bases. I believe you just need the proper folder structure. This is a good example: https://github.com/KristopherKubicki/smartapp-circadian-daylight

**Comment by claytonjn** [comment]
In fact, it looks like you just need to rename the files: https://github.com/KristopherKubicki/smartapp-circadian-daylight/commit/418a9778748aac33d4473bbfe9fddffcb20deead

**Comment by theli-ua** [comment]
+1
You don't need to fork SmartThingsPublic or/and create a new repo
Just rename files in this one and you're good
Makes much more sense imo
