### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke method toInteger() on null object @ line 395

### ISSUE THREAD

**Issue by srpape** [ethayer/user-lock-manager#23]
Sometimes when I click "User Settings", the app displays:

```
"You are not authorized to preform the requested operation."
```

In the logs, I see the following error:

```
java.lang.NullPointerException: Cannot invoke method toInteger() on null object @ line 395
```

So far, I've been uninstalling and reinstalling the app when I need to change user settings.

**Comment by srpape** [comment]
It seems that this happens if I leave any empty slots. I lowered the number of user slots to the exact amount I'm using and haven't seen it since.

**Comment by adobito** [comment]
Can you let me know how to find the logs? I've been trying to fix this error but had no idea what it was exactly.

**Comment by adobito** [comment]
Fixed this, let me send a pull request. 

Still, let me know how to find the logs because I would've never fixed it if it wasn't for your issue.

**Comment by adobito** [comment]
https://github.com/ethayer/user-lock-manager/pull/25

**Comment by srpape** [comment]
In the SmartThings developer website, there's "Live Logging". I just left that open while testing.

There are probably historical logs somewhere on the site as well.

**Comment by ethayer** [comment]
Thanks, this issue has been fixed.
