### ISSUE TITLE
Hello, I'm new, I don't know what to do. Error code at save

### ISSUE THREAD

**Issue by turnerwilliams4** [ethayer/user-lock-manager#26]
Hi I am getting the following error after following the Scott in Pollack video. I deleted the info after preferences on the sample, then added the info from preferences on to the smartthings code area. I recieved these 4 errors when savings. I have a feeling this is something dumb I am doing, but I just can't figure it out. Any help greatly appreciated. I think this app is exactly what I am looking for! 

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script14461616595681943140158.groovy: 1030: unable to resolve class JsonSlurper 
@ line 1030, column 20.
def codeData = new JsonSlurper().parseText(evt.data)
^

script14461616595681943140158.groovy: 1073: unable to resolve class JsonSlurper 
@ line 1073, column 20.
def codeData = new JsonSlurper().parseText(evt.data)
^

script14461616595681943140158.groovy: 1173: unable to resolve class JsonSlurper 
@ line 1173, column 18.
def codeData = new JsonSlurper().parseText(evt.data)
^

script14461616595681943140158.groovy: 1225: unable to resolve class JsonSlurper 
@ line 1225, column 14.
json = new JsonSlurper().parseText(json)
^

4 errors

**Comment by sedeal** [comment]
I am having the exact same issue and am so frustrated!  Following this thread in hopes someone will answer!

**Comment by sedeal** [comment]
I tried again and pasted these two lines above the "preferences" section (which is where the video says to begin if you were following it like I was):

 import groovy.json.JsonSlurper
 import groovy.json.JsonBuilder

It worked for me once I added those in - hope it works for you too, good luck!

**Comment by ethayer** [comment]
Yeah that video is horrible, I need to take that line down on the README.  Thanks for bringing this up.

**Comment by ethayer** [comment]
I wrote a new README with some instructions that should prevent this issue.
