### ISSUE TITLE
isUnique() error with maxUsers being changed from String to Integer

### ISSUE THREAD

**Issue by natecj** [ethayer/user-lock-manager#28]
The recent change of the maxUsers input field from a String to an Integer introduced an error in the method isUnique(). Specifically, the references to newInt.toList() and newInt.length() (and the same for oldInt) should be updated to newInt.toString().toList() and newInt.toString().length(). I can submit a PR later if that helps, but this was easier/faster for the time being.

```
  def i = 0
  // Get a normalized sequence, at the same length
  newInt.toString().toList().collect {
    i++
    if (i <= oldInt.toString().length()) {
      newArray << normalizeNumber(it.toInteger())
    }
  }

  i = 0
  oldInt.toString().toList().collect {
    i++
    if (i <= newInt.toString().length()) {
      oldArray << normalizeNumber(it.toInteger())
    }
  }
```

Lines 420-435

**Comment by ethayer** [comment]
Thank you.
https://github.com/ethayer/user-lock-manager/commit/e9fb09f22c07e75657c31338dcea4eaa0bf71529

**Comment by ethayer** [comment]
just kidding
https://github.com/ethayer/user-lock-manager/commit/30e7d21b918a56ff2e2a8e7cf200603051173117
