### ISSUE TITLE
Z-Wave Lock Reporting Device Type issue

### ISSUE THREAD

**Issue by jriveraiquue** [ethayer/user-lock-manager#29]
I'm experiencing an issue with setting codes on Kwikset 916 Locks using the custom device type. When I switch to the the default Z-Wave Lock Device type I can set codes with no issues. However, on the z-wave lock reporting device type my logs look like this:

```
c56a0bee-b936-4291-943c-6b28b336507e  4:59:00 PM: debug "zw device: 03, command: 9881, payload: 00 63 03 01 00 " parsed to [['name':'codeReport', 'value':1, 'data':['code':''], 'descriptionText':Front Door code 1 is not set, 'displayed':false, 'isStateChange':true, 'linkText':'Front Door']]

c56a0bee-b936-4291-943c-6b28b336507e  4:59:00 PM: debug code report parsed to [['name':'codeReport', 'value':1, 'data':['code':''], 'descriptionText':Front Door code 1 is not set, 'displayed':false, 'isStateChange':true, 'linkText':'Front Door']]

6830d055-265a-49dc-a762-2942f326f4da  4:58:57 PM: debug state: [lastUser:1, userState1:[enabled:true, usage:0], lockc56a0bee-b936-4291-943c-6b28b336507e:[error_loop:false], error_loop_count:0]

6830d055-265a-49dc-a762-2942f326f4da  4:58:55 PM: debug Updating 'Locks' with settings: [userName1:Resident 1, userCode1:1234, userEnabled1:true, maxUsers:1, userSlot1:1, burnCode1:false, dontNotify1:false, theLocks:[Front Door]]

c56a0bee-b936-4291-943c-6b28b336507e  4:58:57 PM: debug setting code 1 to 1234
```

Do you know if SmartThings made any changes that may have broken your custom device type? Any help would be appreciated!

**Comment by scrampker** [comment]
I had major issues today, and almost got locked out of my house. I found a
key, and I had to pull the lock batteries to reset it. Then, like magic, I
was back in business. I had tried manipulating the codes earlier in the day
and never got successful confirmation. Scary!

**Comment by ethayer** [comment]
I know this is long after the fact, but have you had any other experiences like this?  Looks like for some reason the code failed to set and then just didn't try again?  Did it work for other codes?

Are you certain you had the most up to date device handler and that it was active on your device edit menu?

**Comment by jriveraiquue** [comment]
Yes it's good to go. It was a coincidence that there was a smart app outage at the same time as I was trying to set lock codes. 

It's been working fine since then.
