### ISSUE TITLE
I'll pay you to make it work...

### ISSUE THREAD

**Issue by ctennant85** [ethayer/user-lock-manager#30]
Hi I'm a landlord of student share property, I'm planning on buying the Yale lock in the link below. I would like to designate a code to each student valid for a date range and generate a temporary code for tradesmen. I would like to does this remotely. Can you tell me if this would be possible with the program you have written and if not can I pay you to make it work? You can contact me via email ctennant@me.com

Cheers Chris

http://www.yalestore.co.uk/smart-living/keyfree-connected-lock.html

**Comment by ethayer** [comment]
Greetings,

Sorry for being so late on my response.

I think that the app can accommodate your solution, however depending on the number of students you have, it might be cumbersome to make.

I think each student would have to be on their own install of the app.  If you've got 30+ students on one solution, that starts to get busy very quickly.

As this isn't necessarily an issue with the app, I'm going to close the ticket.  Please feel free to email me directly.

erik@thayer.io
