### ISSUE TITLE
Kwikset 910 functionality?

### ISSUE THREAD

**Issue by jarnold3** [ethayer/user-lock-manager#33]
I noticed two Kwikset 910 deadbolts on the manufacturer website.  Z-wave and Zigbee. which one works with lock code manager?  I primarily need to use the scheduling function of lock codes

**Comment by jonrosenberg** [comment]
I have a kwikset 910 zwave and it's works when setting codes. I haven't tried the scheduling feature yet. I also haven't been able to get the data of which codes/users are unlocking and locking the bolt. That is a feature I would like to get working.

**Comment by jarnold3** [comment]
thank you so much for replying!  I wasn't sure anyone would.

I had the Schlage BE469.  its a nice deadbolt, and with that one the push notifications did work and did tell you which user unlocked or locked the deadbolt but the scheduling did not work.  Also codes assigned using the app could not be deleted.

Would you be willing to try the scheduling of the codes in your app and let me know if it works with your Kwikset 910?

Grateful,
John Arnold


---- Jonathan Rosenberg <notifications@github.com> wrote: 
I have a kwikset 910 zwave and it's works when setting codes. I haven't tried the scheduling feature yet. I also haven't been able to get the data of which codes/users are unlocking and locking the bolt. That is a feature I would like to get working.

---

**Comment by jonrosenberg** [comment]
I could probably give it a try this weekend. I am traveling a lot for work this week. I was messing around with the code two nights ago, and started getting error messages, so I probably need to reinstall the app to have a better result.
