### ISSUE TITLE
Power reporting inaccurate?

### ISSUE THREAD

**Issue by trippy99** [ethayer/user-lock-manager#60]
Using a Yale Touchscreen lock and User Lock Manager v4.1.5 and latest Device Handler (I think) and it reports 1% battery while battery seems still good. I rely on this since it's for Airbnb unit and def want to know when to replace batteries. 

How can I debug this? thank you!

**Comment by ethayer** [comment]
I have nothing to do with the power meter code.  That's all from SmartThings.  All 4 of my locks are also reporting only 1%.

SmartThing bug perhaps.

**Comment by trippy99** [comment]
Hey Eric, so what ST support told me was that to get good power reporting, I need to set the locks to "Z-Wave Lock" which is a generic handler that should handle normal commands to just about every z-wave lock out there. I was using a custom one, shown as "Z-Wave Lock Reporting".

Are there known issues using the generic handler for your app?
