### ISSUE TITLE
Missing device handler?

### ISSUE THREAD

**Issue by snornado** [ethayer/user-lock-manager#61]
I'm trying to use the link listed for a new device handler, but getting 404?
https://raw.githubusercontent.com/ethayer/user-lock-manager/master/zwave-lock.groovy

is there an updated link?

Thanks

**Comment by robweber** [comment]
I'm guessing that link is just old - try using the file directly from this repos device handler file: https://raw.githubusercontent.com/ethayer/user-lock-manager/master/devicetypes/smartthings/zwave-lock-reporting.src/zwave-lock-reporting.groovy

**Comment by snornado** [comment]
thank you!
