### ISSUE TITLE
500: Internal Server Error

### ISSUE THREAD

**Issue by wolhwainn** [ethayer/user-lock-manager#67]
When if publish and update from repo, encountered "500: Internal Server Error" with the following message. Any idea?

Error   500:Internal Server Error
URI      /ide/app/doRepoUpdates
Reference Id    44538846-d0c4-4ce3-bf55-70f62a5a16f3
Date    Sun Mar 12 21:23:04 UTC 2017

**Comment by pcartwright81** [comment]
Use the new app in the new respsitory
