### ISSUE TITLE
Issues I'm having with user-lock-manager 3.5

### ISSUE THREAD

**Issue by basssque** [ethayer/user-lock-manager#9]
I have a Kwikset 914 with version 3.5 of the user-lock-manager device type and smart app.
I have programmed 8 codes, none of the codes begin with a zero, but it seems that one code (#7 in this case) doesn't work. If I program 9 codes, another random code does not work any longer.
I also don't receive push notifications on any of our IOS devices anymore since upgrading from an earlier version to 3.5
I cannot lock or unlock the door from the app anymore, the door randomly shows as unlocked in the app, and nothing is logged as far as who enters with what code when or how many times a code has been use.
Any idea's? Thanks

**Comment by ethayer** [comment]
That sounds very strange!  This app should not effect the regular function of the lock.  The only change the device type makes is to add 4 lines of code for reporting, otherwise it's the same code ST uses by default.

*Verify that you copied the device type code in it's entirety into your new custom device type.
*Do the same for the app code, and make sure you didn't mix the two up.
*Unplug your hub, and plug it back in.  (I know, very IT crowed.. but it works to solve some issues)

Post your comment in the (Lock Manager)[http://community.smartthings.com/t/lock-code-manager/12280/] thread in the SmartThings community.  It's possible that some other person had the issues you're experiencing and knows how to fix them.  I'd be very surprised if it was this code specifically.

**Comment by ethayer** [comment]
Also, verify that each of your users have a different user slot entered into the user settings menu.  All 9 codes should work!

Look in the developer IDE logging in the Lock Manager app and see if you see anything interesting.  Could you Post or PM me your settings console log?

**Comment by basssque** [comment]
Where exactly do you want me to pull the logs from, there are a few locations.  I just want to make sure I provide the correct information.  Thanks

**Comment by ethayer** [comment]
https://graph.api.smartthings.com/ide/logs

then click the Lock Manager app when it pops up in the filter menu on top.  While on this page, go into the Lock Manager App and click 'done.'  This will force initialization and cause the app to log your settings to the IDE.

**Comment by basssque** [comment]
code 8 is disabled, FYI

80ae2c3d-6f88-4195-8f53-f5b4cefcc1ce 6:31:28 PM: debug refresh sending ['9881006202']
80ae2c3d-6f88-4195-8f53-f5b4cefcc1ce 6:31:28 PM: debug Kitchen Door Deadbolt Lock is associated to 1
01fa3ca3-0506-46a4-a432-01c740c9bb15 6:31:14 PM: debug msg: Event Notification, and Push Notification: on entry, when granting access, and when revoking access
01fa3ca3-0506-46a4-a432-01c740c9bb15 6:31:14 PM: debug parts: [on entry, when granting access, when revoking access]
01fa3ca3-0506-46a4-a432-01c740c9bb15 6:31:14 PM: debug [userName2:Andy-Becky, userSlot5:5, locks:[Kitchen Door Deadbolt Lock], notification:true, userEnabled2:true, userEnabled4:true, userSlot3:3, userName8:Realtor, userCode7:123456, sendevent:true, notifyAccessStart:true, userSlot9:9, userSlot8:8, maxUsers:8, userEnabled8:false, userName3:Jen-John, userName5:Sheila, notifyAccess:true, userName7:PuppySitter, burnCode2:false, userCode2:234567, userName1:MasterCode, userSlot1:1, burnCode3:false, burnCode4:false, userEnabled6:true, userSlot7:7, burnCode1:false, userEnabled3:true, burnCode6:false, userCode5:678901, userCode8:376951, burnCode8:false, userEnabled7:true, userCode6:567890, burnCode5:false, notifyAccessEnd:true, userEnabled5:true, userCode3:456789, userCode1:345678, userEnabled1:true, userSlot6:6, burnCode7:false, userCode4:789012, userSlot4:4, userName4:Tom-Mary, userName6:Jodi, userSlot2:2]
01fa3ca3-0506-46a4-a432-01c740c9bb15 6:31:14 PM: debug msg: Event Notification, and Push Notification: on entry, when granting access, and when revoking access
01fa3ca3-0506-46a4-a432-01c740c9bb15 6:31:14 PM: debug parts: [on entry, when granting access, when revoking access]
01fa3ca3-0506-46a4-a432-01c740c9bb15 6:31:14 PM: debug [userName2:Andy-Becky, userSlot5:5, locks:[Kitchen Door Deadbolt Lock], notification:true, userEnabled2:true, userEnabled4:true, userSlot3:3, userName8:Realtor, userCode7:123456, sendevent:true, notifyAccessStart:true, userSlot9:9, userSlot8:8, maxUsers:8, userEnabled8:false, userName3:Jen-John, userName5:Sheila, notifyAccess:true, userName7:PuppySitter, burnCode2:false, userCode2:234567, userName1:MasterCode, userSlot1:1, burnCode3:false, burnCode4:false, userEnabled6:true, userSlot7:7, burnCode1:false, userEnabled3:true, burnCode6:false, userCode5:678901, userCode8:376951, burnCode8:false, userEnabled7:true, userCode6:567890, burnCode5:false, notifyAccessEnd:true, userEnabled5:true, userCode3:456789, userCode1:345678, userEnabled1:true, userSlot6:6, burnCode7:false, userCode4:789012, userSlot4:4, userName4:Tom-Mary, userName6:Jodi, userSlot2:2]
01fa3ca3-0506-46a4-a432-01c740c9bb15 6:30:54 PM: debug sendCodes fix is: [["code1","345678"],["code2","234567"],["code3","456789"],["code4","789012"],["code5","678901"],["code6","567890"],["code7","123456"]]
80ae2c3d-6f88-4195-8f53-f5b4cefcc1ce 6:30:54 PM: debug setting code 7 to 123456
80ae2c3d-6f88-4195-8f53-f5b4cefcc1ce 6:30:54 PM: debug code7 was ~bSF6iu4apOuYf4ZPcnERwzgdgh4WtaNTHlam3Iihol0=, set to 123456
80ae2c3d-6f88-4195-8f53-f5b4cefcc1ce 6:30:54 PM: debug setting code 6 to 567890
80ae2c3d-6f88-4195-8f53-f5b4cefcc1ce 6:30:54 PM: debug code6 was , set to 567890
80ae2c3d-6f88-4195-8f53-f5b4cefcc1ce 6:30:54 PM: debug setting code 5 to 678901
80ae2c3d-6f88-4195-8f53-f5b4cefcc1ce 6:30:54 PM: debug code5 was , set to 678901
80ae2c3d-6f88-4195-8f53-f5b4cefcc1ce 6:30:54 PM: debug setting code 4 to 789012
80ae2c3d-6f88-4195-8f53-f5b4cefcc1ce 6:30:54 PM: debug code4 was ~lq7yPVZgiayuIb/aBDQgI7zP3k2hTWN0qQORcjLiFtU=, set to 789012
80ae2c3d-6f88-4195-8f53-f5b4cefcc1ce 6:30:54 PM: debug setting code 3 to 456789
80ae2c3d-6f88-4195-8f53-f5b4cefcc1ce 6:30:54 PM: debug code3 was ~acF+83lGBOZkMR8jqSo7OR9Jqv5mXtiBOc12G7l1xO4=, set to 456789
80ae2c3d-6f88-4195-8f53-f5b4cefcc1ce 6:30:54 PM: debug setting code 2 to 234567
80ae2c3d-6f88-4195-8f53-f5b4cefcc1ce 6:30:54 PM: debug code2 was ~WKj7Yb7SpljdcSgvDbh6UYNpBpGWM+Ov68jg+I8vSU4=, set to 234567
80ae2c3d-6f88-4195-8f53-f5b4cefcc1ce 6:30:54 PM: debug setting code 1 to 345678
80ae2c3d-6f88-4195-8f53-f5b4cefcc1ce 6:30:54 PM: debug code1 was ~UyoyHeEuMK5Il471ZzpFDRWkx5vN2hrUCvWhmGHFk9g=, set to 345678
80ae2c3d-6f88-4195-8f53-f5b4cefcc1ce 6:30:54 PM: debug poll is sending ['9881008002', 'delay 6000'], state: ['code22':'', 'code21':'', 'code24':'', 'code23':'', 'code20':'', 'lastbatt':1429113441705, 'code29':'', 'code25':'', 'code26':'', 'code27':'', 'lastPoll':1429827293355, 'enc':1, 'code28':'', 'MSR':'0090-0001-0001', 'code13':'', 'code12':'', 'assoc':1, 'code11':'', 'code10':'', 'code9':'', 'code6':'', 'code5':'', 'sec':'72 86 98 80 85 70 75 62 63 4E 4C 71 8B 20 5D ', 'code8':'', 'code7':'~bSF6iu4apOuYf4ZPcnERwzgdgh4WtaNTHlam3Iihol0=', 'code2':'~WKj7Yb7SpljdcSgvDbh6UYNpBpGWM+Ov68jg+I8vSU4=', 'codes':30, 'code1':'~UyoyHeEuMK5Il471ZzpFDRWkx5vN2hrUCvWhmGHFk9g=', 'code30':'', 'code4':'~lq7yPVZgiayuIb/aBDQgI7zP3k2hTWN0qQORcjLiFtU=', 'code18':'', 'code19':'', 'code3':'~acF+83lGBOZkMR8jqSo7OR9Jqv5mXtiBOc12G7l1xO4=', 'code16':'', 'code17':'', 'code14':'', 'code15':'']
4f36c7d4-821b-4313-b84f-d37016feec98 6:30:49 PM: info humidityHandler(Thermostat, humidity:36)
1c4bfa43-d557-459c-834d-d63abbd2e0fd 6:30:48 PM: debug checking if it is too high
79968910-6a62-477c-bb7d-a741d20212a6 6:30:48 PM: debug Parse returned [[value:36, unit:%, name:humidity, isStateChange:true, displayed:true, linkText:Thermostat, descriptionText:Thermostat humidity is 36%]]
79968910-6a62-477c-bb7d-a741d20212a6 6:30:48 PM: debug multiinstancev1.MultiInstanceCmdEncap: command from instance 2: SensorMultilevelReport(precision: 0, scale: 0, scaledSensorValue: 36, sensorType: 5, sensorValue: [36], size: 1)
01fa3ca3-0506-46a4-a432-01c740c9bb15 6:30:47 PM: debug msg: Event Notification, and Push Notification: on entry, when granting access, and when revoking access
01fa3ca3-0506-46a4-a432-01c740c9bb15 6:30:47 PM: debug parts: [on entry, when granting access, when revoking access]
01fa3ca3-0506-46a4-a432-01c740c9bb15 6:30:47 PM: debug [userName2:Andy-Becky, userSlot5:5, locks:[Kitchen Door Deadbolt Lock], notification:true, userEnabled2:true, userEnabled4:true, userSlot3:3, userName8:Realtor, userCode7:123456, sendevent:true, notifyAccessStart:true, userSlot9:9, userSlot8:8, maxUsers:8, userEnabled8:false, userName3:Jen-John, userName5:Sheila, notifyAccess:true, userName7:PuppySitter, burnCode2:false, userCode2:234567, userName1:MasterCode, userSlot1:1, burnCode3:false, burnCode4:false, userEnabled6:true, userSlot7:7, burnCode1:false, userEnabled3:true, burnCode6:false, userCode5:678901, userCode8:376951, burnCode8:false, userEnabled7:true, userCode6:567890, burnCode5:false, notifyAccessEnd:true, userEnabled5:true, userCode3:456789, userCode1:345678, userEnabled1:true, userSlot6:6, burnCode7:false, userCode4:789012, userSlot4:4, userName4:Tom-Mary, userName6:Jodi, userSlot2:2]
01fa3ca3-0506-46a4-a432-01c740c9bb15 6:30:47 PM: debug msg: Event Notification, and Push Notification: on entry, when granting access, and when revoking access
01fa3ca3-0506-46a4-a432-01c740c9bb15 6:30:47 PM: debug parts: [on entry, when granting access, when revoking access]
01fa3ca3-0506-46a4-a432-01c740c9bb15 6:30:47 PM: debug [userName2:Andy-Becky, userSlot5:5, locks:[Kitchen Door Deadbolt Lock], notification:true, userEnabled2:true, userEnabled4:true, userSlot3:3, userName8:Realtor, userCode7:123456, sendevent:true, notifyAccessStart:true, userSlot9:9, userSlot8:8, maxUsers:8, userEnabled8:false, userName3:Jen-John, userName5:Sheila, notifyAccess:true, userName7:PuppySitter, burnCode2:false, userCode2:234567, userName1:MasterCode, userSlot1:1, burnCode3:false, burnCode4:false, userEnabled6:true, userSlot7:7, burnCode1:false, userEnabled3:true, burnCode6:false, userCode5:678901, userCode8:376951, burnCode8:false, userEnabled7:true, userCode6:567890, burnCode5:false, notifyAccessEnd:true, userEnabled5:true, userCode3:456789, userCode1:345678, userEnabled1:true, userSlot6:6, burnCode7:false, userCode4:789012, userSlot4:4, userName4:Tom-Mary, userName6:Jodi, userSlot2:2]
79968910-6a62-477c-bb7d-a741d20212a6 6:30:39 PM: debug Parse returned [[value:heating, name:thermostatOperatingState, isStateChange:false, displayed:false, linkText:Thermostat, descriptionText:Thermostat thermostat operating state is heating]]
79968910-6a62-477c-bb7d-a741d20212a6 6:30:37 PM: debug Parse returned [[value:fanOn, name:thermostatFanMode, displayed:false, isStateChange:false, linkText:Thermostat, descriptionText:Thermostat thermostat fan mode is fanOn]]
79968910-6a62-477c-bb7d-a741d20212a6 6:30:34 PM: debug Parse returned [[value:heat, name:thermostatMode, isStateChange:false, displayed:false, linkText:Thermostat, descriptionText:Thermostat thermostat mode is heat]]
79968910-6a62-477c-bb7d-a741d20212a6 6:30:32 PM: debug Parse returned [[value:80, unit:F, displayed:false, name:coolingSetpoint, isStateChange:false, linkText:Thermostat, descriptionText:Thermostat cooling setpoint is 80°F]]
79968910-6a62-477c-bb7d-a741d20212a6 6:30:30 PM: debug Parse returned [[value:69, unit:F, displayed:false, name:heatingSetpoint, isStateChange:false, linkText:Thermostat, descriptionText:Thermostat heating setpoint is 69°F]]
2094e8c4-ed98-4757-aaa9-71362baf87d3 6:30:28 PM: debug Sirens are off
2094e8c4-ed98-4757-aaa9-71362baf87d3 6:30:28 PM: info temperatureHandler(Thermostat, temperature:66.0)
62dfc4e4-7e0c-45c3-b147-361ae7807399 6:30:28 PM: info temperatureHandler(Thermostat, temperature:66.0)
5d4ef212-b348-4e58-a450-ed94f78e9259 6:30:28 PM: debug checking if it is too hot
5d4ef212-b348-4e58-a450-ed94f78e9259 6:30:28 PM: debug checking if it is too cold
79968910-6a62-477c-bb7d-a741d20212a6 6:30:28 PM: debug Parse returned [[value:66.0, unit:F, name:temperature, isStateChange:true, displayed:true, linkText:Thermostat, descriptionText:Thermostat temperature is 66.0°F]]
79968910-6a62-477c-bb7d-a741d20212a6 6:30:26 PM: debug Clock set age: 1300.0110166667 minutes
79968910-6a62-477c-bb7d-a741d20212a6 6:30:26 PM: debug Battery report age: 1297.9141833333 minutes
01fa3ca3-0506-46a4-a432-01c740c9bb15 6:30:25 PM: debug msg: Event Notification, and Push Notification: on entry, when granting access, and when revoking access
01fa3ca3-0506-46a4-a432-01c740c9bb15 6:30:25 PM: debug parts: [on entry, when granting access, when revoking access]
01fa3ca3-0506-46a4-a432-01c740c9bb15 6:30:25 PM: debug [userName2:Andy-Becky, userSlot5:5, locks:[Kitchen Door Deadbolt Lock], notification:true, userEnabled2:true, userEnabled4:true, userSlot3:3, userName8:Realtor, userCode7:123456, sendevent:true, notifyAccessStart:true, userSlot9:9, userSlot8:8, maxUsers:8, userEnabled8:false, userName3:Jen-John, userName5:Sheila, notifyAccess:true, userName7:PuppySitter, burnCode2:false, userCode2:234567, userName1:MasterCode, userSlot1:1, burnCode3:false, burnCode4:false, userEnabled6:true, userSlot7:7, burnCode1:false, userEnabled3:true, burnCode6:false, userCode5:678901, userCode8:376951, burnCode8:false, userEnabled7:true, userCode6:567890, burnCode5:false, notifyAccessEnd:true, userEnabled5:true, userCode3:456789, userCode1:345678, userEnabled1:true, userSlot6:6, burnCode7:false, userCode4:789012, userSlot4:4, userName4:Tom-Mary, userName6:Jodi, userSlot2:2]
01fa3ca3-0506-46a4-a432-01c740c9bb15 6:30:25 PM: debug msg: Event Notification, and Push Notification: on entry, when granting access, and when revoking access
01fa3ca3-0506-46a4-a432-01c740c9bb15 6:30:25 PM: debug parts: [on entry, when granting access, when revoking access]
01fa3ca3-0506-46a4-a432-01c740c9bb15 6:30:25 PM: debug [userName2:Andy-Becky, userSlot5:5, locks:[Kitchen Door Deadbolt Lock], notification:true, userEnabled2:true, userEnabled4:true, userSlot3:3, userName8:Realtor, userCode7:123456, sendevent:true, notifyAccessStart:true, userSlot9:9, userSlot8:8, maxUsers:8, userEnabled8:false, userName3:Jen-John, userName5:Sheila, notifyAccess:true, userName7:PuppySitter, burnCode2:false, userCode2:234567, userName1:MasterCode, userSlot1:1, burnCode3:false, burnCode4:false, userEnabled6:true, userSlot7:7, burnCode1:false, userEnabled3:true, burnCode6:false, userCode5:678901, userCode8:376951, burnCode8:false, userEnabled7:true, userCode6:567890, burnCode5:false, notifyAccessEnd:true, userEnabled5:true, userCode3:456789, userCode1:345678, userEnabled1:true, userSlot6:6, burnCode7:false, userCode4:789012, userSlot4:4, userName4:Tom-Mary, userName6:Jodi, userSlot2:2]
8e36660d-cdbe-4b59-9c34-d12718e76060 6:30:10 PM: trace getPhrases(), state.welcomeIssue = null
6:29:38 PM: info Waiting on events...
6:29:38 PM: info For past logs for individual things go to the My Devices section, find the device and click on the Events link on the device information page.
6:29:38 PM: info This console provides live logging of your SmartThings.

**Comment by basssque** [comment]
Anything stand out?

**Comment by ethayer** [comment]
I'm not sure if you've been following the community forums at all, but I think that we have this figured out.  It seems like one or more of your codes violates a validation rule.

See this post about the subject, and some subsequent posts after that:
http://community.smartthings.com/t/lock-code-manager/12280/121?u=ethayer
